# Generated by Django 5.2.8 on 2025-11-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('summary_json', models.TextField(blank=True, default='{}')),
                ('row_count', models.IntegerField(default=0)),
            ],
        ),
    ]
